### ISSUE TITLE
need Of WAV fromat

### ISSUE THREAD

**Issue by coderatul** [Android-for-Python/record_audio_example#1]
hey the examples you have provided are amazing and pretty helpful !!!

I am trying to build an audio recording app, but i want to record in lossless format (wav) , and after doing some research i found an Android api [AudioRecord](https://developer.android.com/reference/android/media/AudioRecord) using which we may record in PCM fromat and later convert it to WAV, could please upload an example using AudioRecord API

**Comment by Android-for-Python** [comment]
These are examples, if you want something else that is up to you.
have fun
